// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelProcess() {
  return window['go']['main']['App']['CancelProcess']();
}

export function CompressBatch(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['CompressBatch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function FastSync(arg1, arg2, arg3) {
  return window['go']['main']['App']['FastSync'](arg1, arg2, arg3);
}

export function MergeVideos(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MergeVideos'](arg1, arg2, arg3, arg4);
}

export function RunSync(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['RunSync'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SelectAudio() {
  return window['go']['main']['App']['SelectAudio']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectMultipleVideos() {
  return window['go']['main']['App']['SelectMultipleVideos']();
}

export function SelectVideo() {
  return window['go']['main']['App']['SelectVideo']();
}

export function SplitWideCamera(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SplitWideCamera'](arg1, arg2, arg3, arg4);
}

export function StartServer(arg1, arg2) {
  return window['go']['main']['App']['StartServer'](arg1, arg2);
}

export function StartTgBot(arg1, arg2) {
  return window['go']['main']['App']['StartTgBot'](arg1, arg2);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function StopTgBot() {
  return window['go']['main']['App']['StopTgBot']();
}
