// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelProcess():Promise<void>;

export function CompressBatch(arg1:Array<string>,arg2:number,arg3:string,arg4:boolean,arg5:boolean,arg6:boolean,arg7:boolean,arg8:string,arg9:string,arg10:string):Promise<string>;

export function FastSync(arg1:string,arg2:string,arg3:string):Promise<string>;

export function MergeVideos(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RunSync(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number,arg9:string,arg10:number):Promise<string>;

export function SelectAudio():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectMultipleVideos():Promise<Array<string>>;

export function SelectVideo():Promise<string>;

export function SplitWideCamera(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function StartServer(arg1:string,arg2:string):Promise<string>;

export function StartTgBot(arg1:string,arg2:string):Promise<string>;

export function StopServer():Promise<void>;

export function StopTgBot():Promise<void>;
